import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#6f7975",
        "tertiary-fixed": "#dbe1ff",
        "on-secondary-container": "#4d6b5e",
        "on-tertiary-fixed": "#00174b",
        primary: "#076450",
        "on-surface-variant": "#3f4945",
        "surface-variant": "#d8e3fb",
        "primary-fixed": "#a4f2d8",
        background: "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "on-error-container": "#93000a",
        "on-background": "#111c2d",
        "surface-dim": "#cfdaf2",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed-variant": "#304c41",
        "secondary-fixed-dim": "#aecebf",
        "primary-fixed-dim": "#88d5bd",
        "inverse-surface": "#263143",
        "surface-container-highest": "#d8e3fb",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "tertiary-container": "#2a66ee",
        "outline-variant": "#bec9c3",
        "on-surface": "#111c2d",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "surface-tint": "#156b56",
        tertiary: "#004dcc",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#c9eada",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#022017",
        "inverse-primary": "#88d5bd",
        "on-primary-fixed": "#002018",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-primary-fixed-variant": "#005140",
        secondary: "#476458",
        "secondary-container": "#c9eada",
        surface: "#f9f9ff",
        "on-tertiary-container": "#f4f4ff",
        "on-primary": "#ffffff",
        "primary-container": "#2e7d68",
        "surface-container": "#e7eeff",
        "on-primary-container": "#d3ffee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-lg": "2.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter-md": "1.5rem",
        gutter: "1rem",
        margin: "1rem",
        "margin-md": "1.5rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "gutter-lg": "2rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "token-display": ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
